Update yamllint.yml

diff --git a/.github/workflows/yamllint.yml b/.github/workflows/yamllint.yml
--- a/.github/workflows/yamllint.yml
+++ b/.github/workflows/yamllint.yml
@@ -19,7 +19,13 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - name: Install YAMLLint
         shell: bash
-        run: sudo pip install yamllint==1.35.1
+        run: |
+          pip install yamllint==1.35.1
+          msg="$(pip list --outdated | grep -e yamllint || true)"
+          if [ -n "${msg}" ]; then
+            >&2 echo "ERROR: outdated: ${msg}"
+            exit 1
+          fi
       - name: Run YAMLLint
         shell: bash
-        run: "yamllint -d '{extends: relaxed, rules: {line-length: disable, trailing-spaces: disable}}' ."
+        run: "yamllint -d '{extends: default, rules: {line-length: disable}}' ."
